name: ISeeYou-Fork
version: ${version}
main: xaviermc.top.iseeyou.ISeeYou
api-version: '1.20'
dependencies:
  server:
    Themis:
      load: BEFORE
      required: false
    Matrix:
      load: BEFORE
      required: false
